#!/usr/bin/env python3
import argparse
import json
import os
import sys
import time
from pathlib import Path

import boto3


def _load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key, value)


def _build_event(body: str) -> dict:
    payload = json.loads(body)
    # SQS body from an SNS subscription contains a nested JSON envelope.
    message = payload.get("Message", "{}") if isinstance(payload, dict) else "{}"
    return {
        "Records": [
            {
                "Sns": {
                    "Type": payload.get("Type", "Notification") if isinstance(payload, dict) else "Notification",
                    "Message": message,
                }
            }
        ]
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Local SQS poller that invokes lambda/handler.py")
    parser.add_argument("--env-file", default=".env.localtest", help="Path to env file generated by local bootstrap")
    parser.add_argument("--once", action="store_true", help="Process at most one message and exit")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    _load_env_file(repo_root / args.env_file)

    required = [
        "AWS_DEFAULT_REGION",
        "AWS_ENDPOINT_URL",
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY",
        "RESPONDER_QUEUE_URL",
        "KUBECONFIG_BUCKET",
    ]
    missing = [k for k in required if not os.environ.get(k)]
    if missing:
        print(f"Missing required environment variables: {', '.join(missing)}", file=sys.stderr)
        return 1

    # Ensure local kubeconfig auth is used for kind/minikube.
    os.environ.setdefault("K8S_AUTH_MODE", "kubeconfig")

    sys.path.insert(0, str(repo_root / "lambda"))
    import handler  # noqa: E402

    sqs = boto3.client(
        "sqs",
        region_name=os.environ["AWS_DEFAULT_REGION"],
        endpoint_url=os.environ["AWS_ENDPOINT_URL"],
        aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"],
    )

    queue_url = os.environ["RESPONDER_QUEUE_URL"]
    processed = 0

    print("Local responder started; polling queue:", queue_url)
    while True:
        resp = sqs.receive_message(
            QueueUrl=queue_url,
            MaxNumberOfMessages=1,
            WaitTimeSeconds=10,
            VisibilityTimeout=30,
        )
        messages = resp.get("Messages", [])
        if not messages:
            if args.once:
                break
            continue

        msg = messages[0]
        receipt = msg["ReceiptHandle"]
        body = msg.get("Body", "{}")
        try:
            event = _build_event(body)
            handler.handler(event, None)
            sqs.delete_message(QueueUrl=queue_url, ReceiptHandle=receipt)
            processed += 1
            print(f"Processed message count={processed}")
            if args.once:
                break
        except Exception as exc:  # noqa: BLE001
            print(f"Failed to process message: {exc}", file=sys.stderr)
            if args.once:
                return 1
            time.sleep(1)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
